---
- name: Install Webserver
  hosts: webserver
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
       update_cache: yes

    - name: Restart & Enabled Apache2
      service:
        name: apache2
        state: started
        enabled: yes