---
- name: install dns
  hosts: dns
  become: true
  tasks:
    - name: Install Dependencies
      apt: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - bind9
      - dnsutils

    - name: start dns service
      service:
        name: bind9
        state: started
        enabled: true